Add Echo Dot
EtiennePerot/macchiato pull request #16
Opened 2016-09-14 18:44 UTC by i-ghost

Amazon.com, Inc Echo Dot (1st gen)

2016-09-17 21:06 UTC, EtiennePerot commented on oui/wireless_pmp.sh
> +	f0:27:2D='Amazon.com, Inc.|Echo Dot'
Lowercase D.

Also, per ieee.org, it's `Amazon Technologies Inc.`.

2016-09-17 21:06 UTC, EtiennePerot requested changes

2016-09-20 20:47 UTC, i-ghost commented
Fixed in 4fc3d29.

2016-09-20 21:29 UTC, EtiennePerot approved these changes

2016-09-20 21:35 UTC, merged